<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Entity\SchoolLevel;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\PropertyAccess\PropertyAccessor;

class SchoolLevelFixtures extends Fixture
{
    /**
     * @var array<string, array{
     *  name: string,
     *  internalName?: string,
     *  type: string,
     *  level: string,
     *  capacityRequired: boolean,
     *  capacityReachedRequired: true,
     *  capacityReachedAtRequired: true,
     *  indicatorStudentSeatsPercentageRequired: boolean,
     *  indicatorStudentSeatsRequired: boolean,
     *  studentSeatsRequired: boolean,
     *  formTypeRequired: boolean,
     *  typeRequired: boolean,
     *  administrativeGroupsRequired: boolean,
     *  nameRequired: boolean,
     *  gradeRequired: boolean,
     *  phaseRequired: boolean,
     *  maxEducations: null|int,
     *  position: int,
     *  defaultRequired?: boolean,
     *  defaultDeletable?: boolean,
     * }>
     */
    public static array $schoolLevels = [
        '1ste_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '1ste middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => true,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => true,
            'internalName' => SchoolLevel::INTERNAL_NAME_SECONDARY_REGULAR_EDUCATION_FIRST_GRADE,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 1,
            'educationsFilterVisible' => true,
        ],
        '2de_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '2de middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 2,
            'educationsFilterVisible' => true,
        ],
        '3de_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '3de middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 3,
            'educationsFilterVisible' => true,
        ],
        '4de_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '4de middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 4,
            'educationsFilterVisible' => true,
        ],
        '5de_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '5de middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 5,
            'educationsFilterVisible' => true,
        ],
        '6de_middelbaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '6de middelbaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 6,
            'educationsFilterVisible' => true,
        ],
        'se_n_se_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => 'Se-n-Se',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 8,
            'educationsFilterVisible' => true,
        ],
        '7e_jaar_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => '7e jaar',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 7,
            'educationsFilterVisible' => true,
        ],
        'onthaalonderwijs_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_RECEPTION_EDUCATION => [
            'name' => 'Onthaalonderwijs',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_RECEPTION_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => false,
            'formTypeRequired' => true,
            'typeRequired' => false,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => 1,
            'position' => 9,
        ],
        'kleuter_' . SchoolLevel::TYPE_PRE_PRIMARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Kleuter',
            'type' => SchoolLevel::TYPE_PRE_PRIMARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => true,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => false,
            'nameRequired' => false,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 1,
            'defaultRequired' => true,
            'defaultDeletable' => false,
        ],
        'lager_' . SchoolLevel::TYPE_PRIMARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Lager',
            'type' => SchoolLevel::TYPE_PRIMARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => true,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => false,
            'nameRequired' => false,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 2,
            'defaultRequired' => true,
            'defaultDeletable' => false,
        ],
        'kleuter_' . SchoolLevel::TYPE_PRE_PRIMARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => 'Kleuter',
            'type' => SchoolLevel::TYPE_PRE_PRIMARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'internalName' => SchoolLevel::INTERNAL_NAME_PRE_PRIMARY_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => true,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => false,
            'administrativeGroupsRequired' => false,
            'nameRequired' => false,
            'gradeRequired' => true,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 1,
            'defaultRequired' => true,
            'defaultDeletable' => true,
        ],
        'lager_' . SchoolLevel::TYPE_PRIMARY_EDUCATION . '_' . SchoolLevel::LEVEL_REGULAR_EDUCATION => [
            'name' => 'Lager',
            'type' => SchoolLevel::TYPE_PRIMARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_REGULAR_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => true,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => false,
            'administrativeGroupsRequired' => false,
            'nameRequired' => false,
            'gradeRequired' => true,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 2,
            'defaultRequired' => true,
            'defaultDeletable' => true,
        ],
        'reception_education_' . SchoolLevel::TYPE_PRIMARY_EDUCATION . '_' . SchoolLevel::LEVEL_RECEPTION_EDUCATION => [
            'name' => 'Onthaalonderwijs',
            'type' => SchoolLevel::TYPE_PRIMARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_RECEPTION_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => true,
            'studentSeatsRequired' => false,
            'formTypeRequired' => false,
            'typeRequired' => false,
            'administrativeGroupsRequired' => false,
            'nameRequired' => false,
            'gradeRequired' => true,
            'phaseRequired' => false,
            'maxEducations' => 1,
            'defaultRequired' => true,
            'defaultDeletable' => false,
            'position' => 2,
        ],
        'ov1_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Opleidingsvorm 1 (OV1)',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => false,
            'maxEducations' => null,
            'position' => 1,
            'schoolTypeFilterVisible' => true,
        ],
        'ov2_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Opleidingsvorm 2 (OV2)',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => false,
            'phaseRequired' => true,
            'phaseFilterVisible' => true,
            'maxEducations' => null,
            'position' => 2,
            'schoolTypeFilterVisible' => true,
        ],
        'ov3_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Opleidingsvorm 3 (OV3)',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => true,
            'phaseRequired' => true,
            'phaseFilterVisible' => true,
            'gradeFilterVisible' => true,
            'educationsFilterVisible' => true,
            'maxEducations' => null,
            'position' => 3,
            'schoolTypeFilterVisible' => true,
        ],
        'ov4_' . SchoolLevel::TYPE_SECONDARY_EDUCATION . '_' . SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION => [
            'name' => 'Opleidingsvorm 4 (OV4)',
            'type' => SchoolLevel::TYPE_SECONDARY_EDUCATION,
            'level' => SchoolLevel::LEVEL_SPECIAL_NEEDS_EDUCATION,
            'capacityRequired' => true,
            'capacityReachedRequired' => true,
            'capacityReachedAtRequired' => true,
            'indicatorStudentSeatsPercentageRequired' => false,
            'indicatorStudentSeatsRequired' => false,
            'studentSeatsRequired' => true,
            'formTypeRequired' => false,
            'typeRequired' => true,
            'administrativeGroupsRequired' => true,
            'nameRequired' => true,
            'gradeRequired' => true,
            'phaseRequired' => false,
            'gradeFilterVisible' => true,
            'educationsFilterVisible' => true,
            'maxEducations' => null,
            'position' => 4,
            'schoolTypeFilterVisible' => true,
        ],
    ];

    public function load(ObjectManager $manager): void
    {
        foreach (self::$schoolLevels as $reference => $schoolLevelData) {
            $propertyAccessor = new PropertyAccessor();
            $schoolLevel = new SchoolLevel();
            foreach ($schoolLevelData as $field => $value) {
                $propertyAccessor->setValue($schoolLevel, $field, $value);
            }

            if ($schoolLevel instanceof SchoolLevel) {
                $manager->persist($schoolLevel);
                $this->setReference($reference, $schoolLevel);
            }
        }

        $manager->flush();
    }
}
